# -*- coding: utf-8 -*-
"""Dungeon Crawler

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cRMZiYK53xcrDRIAypUjwdF-6--rlmEB
"""

import os
import keyboard
clear = lambda: os.system('cls')
class playMat:
    length = 7;
    def __init__(self):
      self.board = ['*'] * length * length
    def __str___(self):
      s = ""
      for x in [0, length, 2*length]:
        s += f"{self.board[x]} {self.board[x + 1]} {self.board[x + 2]}\n"
def replacer(s, newString, index):
    return s[:index - 1] + newString + s[index + 1]

maparray=[]

maparray.append("...........xxxxxxxxxx...........")
maparray.append("...........x........x...........")
maparray.append(maparray[1]) 
maparray.append(maparray[1]) 
maparray.append(maparray[1]) 
maparray.append(maparray[1]) 
maparray.append(maparray[0]) 
maparray.append("..............x..x..............")
maparray.append(maparray[7]) 
maparray.append("xxxxxxxxx..xxxxxxxxxx..xxxxxxxxx")
maparray.append("x.......x..x........x..x.......x")
maparray.append("x.......xxxx........xxxx.......x")
maparray.append(maparray[10])
maparray.append(maparray[11])
maparray.append(maparray[10])
maparray.append(maparray[9])

for x in maparray:
	print(x)

class Player:
	def _init_(self, character):
		self.character = character
		self.xp = 15 
		self.yp = 2 
	"""def put_in_map(self):
		startingrow = maparray[self.yp]
		startingrow[self.xp] = self.character
    """
main = Player()
print(main.xp)

class Monster:
  def __init__(self, name, health, strength):
    self.name = name
    self.age = health
    self.strength = strength

p1 = Monster("Goblin", 20,2)
p2 = Monster("Troll", 35, 3)
print(p1.name)
print(p2.name)

print("...........xxxxxxxxxx...........")
print("...........x........x...........")
print("...........x........x...........")
print("...........x........x...........")
print("...........x........x...........")
print("...........x........x...........")
print("...........xxxxxxxxxx...........")
print("..............x..x..............")
print("..............x..x..............")
print("xxxxxxxxx..xxxxxxxxxx..xxxxxxxxx")
print("x.......x..x........x..x.......x")
print("x.......xxxx........xxxx.......x")
print("x.......x..x........x..x.......x")
print("x.......xxxx........xxxx.......x")
print("x.......x..x....@...x..x.......x")
print("xxxxxxxxx..xxxxxxxxxx..xxxxxxxxx")
test = "x.......x..x....@...x..x.......x"
print(test.find("@",0,32))

greg = player
if keyboard.is_pressed('w'):
    greg.yposition = greg.yposition - 1
    
    clear()
if keyboard.is_pressed('a'):
    greg.xposition = greg.xposition - 1
if keyboard.is_pressed('s'):
    greg.yposition = greg.yposition + 1
if keyboard.is_pressed('d'):
    greg.xposition = greg.xposition + 1